server:
  port: 8080

spring:
  application:
    name: zr-platform-backend
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info

zr:
  security:
    jwt:
      issuer: zr-platform
      secret: change-me-to-32bytes-minimum-secret
      access-ttl-seconds: 1200
      refresh-ttl-seconds: 1209600

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ai:
  schedule:
    enabled: true

# 高德地图配置
amap:
  key: ${AMAP_KEY:a0e376b4b78219135989c322f81b9ef8}
  securityConfig: ${AMAP_SECURITY_CONFIG:c9cdb1e7314ce353f3573610415fea0b}
